version: '3.8'

services:
  db:
    image: mysql:8.0
    # platform: linux/amd64
    platform: linux/x86_64 # mac m1칩
    container_name: delivery_web_db
    env_file:
      - '.env.local'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      LANG: C.UTF_8
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 10s
      timeout: 60s
      retries: 10

  redis:
    image: redis:alpine
    platform: linux/amd64
    container_name: delivery_web_redis
    restart: always
    ports:
      - '6379:6379'
